services:
  postgres:
    image: postgres:17

    container_name: chulbul-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chulbul_bank

    ports:
      - "3015:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4

    container_name: chulbul-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chulbul.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

volumes:
  postgres_data: